ALTER TABLE DM_DEVICE_TYPE  ADD COLUMN LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DM_DEVICE_TYPE  ADD COLUMN DEVICE_TYPE_META  VARCHAR(20000) DEFAULT NULL;
ALTER TABLE DM_ENROLMENT_OP_MAPPING ADD COLUMN PUSH_NOTIFICATION_STATUS VARCHAR(50) NULL;
UPDATE DM_ENROLMENT_OP_MAPPING SET PUSH_NOTIFICATION_STATUS = 'COMPLETED';
ALTER TABLE DM_CONFIG_OPERATION  ADD COLUMN ENABLED BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS DM_DEVICE_PROPERTIES (
     DEVICE_TYPE_NAME VARCHAR(300) NOT NULL,
     DEVICE_IDENTIFICATION VARCHAR(300) NOT NULL,
     PROPERTY_NAME VARCHAR(100) DEFAULT 0,
     PROPERTY_VALUE VARCHAR(100) DEFAULT NULL,
     TENANT_ID VARCHAR(100) DEFAULT NULL,
     PRIMARY KEY (DEVICE_TYPE_NAME, DEVICE_IDENTIFICATION, PROPERTY_NAME, TENANT_ID)
);