ALTER TABLE DM_DEVICE_TYPE  ADD COLUMN LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE DM_DEVICE_TYPE  ADD COLUMN DEVICE_TYPE_META  VARCHAR(20000) DEFAULT NULL;
ALTER TABLE DM_ENROLMENT_OP_MAPPING ADD COLUMN PUSH_NOTIFICATION_STATUS VARCHAR(50) NULL;
UPDATE DM_ENROLMENT_OP_MAPPING SET PUSH_NOTIFICATION_STATUS = 'COMPLETED';