ALTER TABLE AD_DEVICE
CHANGE COLUMN GCM_TOKEN FCM_TOKEN VARCHAR(1000) NULL DEFAULT NULL;

-- Run the following only if the both EMM 2.1.0 and IoT 3.3.1 has to run simultaneously.

ALTER TABLE AD_DEVICE
ADD COLUMN GCM_TOKEN VARCHAR(1000) NULL AFTER OS_BUILD_DATE;
